### ISSUE TITLE
Poor contrast in some native KDE apps (Discover, Settings)

### ISSUE THREAD

**Issue by suryaya** [catppuccin/kde#21] opened 2022-12-02 06:35 UTC
Hello again, thanks again for improving the theme based on user feedback.

Found a few more visual glitches around KDE.

1. Selecting an item from the 'Update' list:

![image](https://user-images.githubusercontent.com/59785388/205230345-32a2bb1e-b625-4a7a-a89a-b5ca8c986005.png)

2. In the settings, go to Input Devices > Keyboard > Layouts. Add a layout. Now select it and tick 'spare layouts'. Results in poor contrast between text color and background.

![image](https://user-images.githubusercontent.com/59785388/205230586-37df2330-e1c0-46e5-a617-bb7c577c84c8.png)

**Comment by Sourcastic** [comment] 2022-12-02 16:46
Hi, thanks for the issue. 
As far as I can tell, though, these two things are KDE bugs/issues. I'm not sure if they're intentional or not, but regardless, I doubt I can fix them. I'll keep this open, since I don't have an update in discover yet, so I'll wait till I can reproduce that.

**Comment by Sourcastic** [comment] 2022-12-03 19:39
Actually, possibly, but kind of drastic solution that'd fix it in a lot of places: Just change to a darker accent colour by default. There will eventually be a script on the repo to choose your accent colour, but this would work as flamingo is a much lighter colour than (say) blue (good because we don't use that elsewhere): 

![image](https://user-images.githubusercontent.com/79325941/205456256-7bfe1564-8118-425c-8131-76fa228ba97e.png)

Still not ideal since it's not perfect contrast and of course we want for people to be able to use any accent colour, especially after adding the script. Plus, changing it... I'm not sure. I could throw that in the same commit with the bash script. Thoughts?

**Comment by suryaya** [comment] 2022-12-03 21:45
Well, I'm definitely not a UI artist, I only report bugs 😂. Personally I really like the flamingo color choice, it makes the theme more interesting in a way that blue on blue just doesn't. Though it's up to you in the end, blue still looks nice.

For now, I just changed the 'view text' color in the editor to something very slightly darker, just enough for me to read.

![image](https://user-images.githubusercontent.com/59785388/205463342-c87ee5f5-fda6-48d8-97d2-5213857d2e09.png)

**Comment by Sourcastic** [comment] 2022-12-04 08:12
> I'm definitely not a UI artist

Haha, I'm not either :sweat_smile: . But I try my best. 

Yeah, I'll just wait till a bash script makes it to the repo then decide it on a default accent. Though, I wish KDE used highlighted text colour here instead. I don't think I can do anything about the second layout page issue.

**Comment by Sourcastic** [comment] 2023-01-19 18:09
So, there is a bash script now meaning you can now choose a darker accent, and it makes the text in discover slightly more readable. Unfortunately, it's a problem with KDE itself and I can't fix the text colour without harming the other parts of the theme, and I'll close the issue now.

**Closed** 2023-01-19 18:09 UTC
