### ISSUE TITLE
Global menu widget colour inconsistency

### ISSUE THREAD

**Issue by azymandiasAR** [catppuccin/kde#5] opened 2022-08-27 08:12 UTC
(using the global KDE theme as well as the Kvantum one)

When hovering over a button in the global menu [File/Edit/View..] this happens:
![Screenshot_20220827_134151](https://user-images.githubusercontent.com/78789258/187021491-9e1d5677-1451-4a73-b234-0fe78eaed885.png)

**Comment by Sourcastic** [comment] 2023-01-19 18:07
Hi, since this issue was made, we've updated the port to have the newer flavours and was re-made from the ground up. I can't reproduce the issue now, so I'll close this issue. Re-open it/make a new one if you find it's still an issue.

**Closed by Sourcastic** 2023-01-19 18:07 UTC
