### ISSUE TITLE
Theme metadata / installer need a KF6 port

### ISSUE THREAD

**Issue by dinckelman** [catppuccin/kde#52] opened 2024-02-22 23:22 UTC
At the moment, practically nothing in the repo builds for Plasma 6, despite it supporting Qt6 styles. A new packaging and metadata format have been introduced, with a porting procedure described [here](https://develop.kde.org/docs/plasma/theme/theme-porting-to-plasma6/)

**Comment by Sourcastic** [comment] 2024-02-26 12:54
Thank you for bringing this up, I wasn't aware the changes would be breaking.

I'll try to work on this in my spare time and port it to kde6 some time in the near future!

**Comment by pluiedev** [comment] 2024-03-05 09:10
Just switched to Plasma 6 and was a bit bummed that the theme didn't work OOTB — might look into porting it myself soon-ish

**Comment by Sourcastic** [comment] 2024-03-05 10:49
@pluiedev I'll add the work I've done so far to the `dev` branch. It mostly consists of adding metadata.json to everything. What's left is adapting the script. There are some problems in the global theme dependencies though, as it imports the old plasma5 aurorae theme for now. It will likely have to involve adding the ported aurorae theme to the store.

Any suggestions and help are welcome :).

**Comment by Sourcastic** [comment] 2024-03-05 16:18
For now, it'd be greatly appreciated if someone could test the updated aurorae theme. All you'll need to do is clone the repo, shift to the dev branch and see if copying anything from Resources/Aurorae to ~/.local/share/aurorae/themes works?

**Comment by dinckelman** [comment] 2024-03-05 17:18
Just tried it out on RC2. With some manual intervention, the decorations load seemingly correctly.

Since the installer is not there yet, `Catppuccin-Modernrc` from common has to be manually placed in the theme folder, and renamed `CatppuccinMacchiato-Modernrc`, for example. Otherwise the theme defaults to Plastik entirely

**Comment by dinckelman** [comment] 2024-03-05 19:27
No problem. I've found some time to take a look at the install script in the meantime. Should be good to go soon, or otherwise I'll just create a pr for what I got working

**Comment by dinckelman** [comment] 2024-03-05 20:21
Script patch [ready](https://github.com/catppuccin/kde/pull/55) for review

**Comment by KeebCat** [comment] 2024-03-10 10:28
Hi, I'd be curious on if the theme actually works for Plasma 6 now? Judging by the pull request it seems to be like 95% of the way there, but not quite?

**Comment by Sourcastic** [comment] 2024-03-10 11:36
You're right, it is 95% of the way there.
 I just want to get splashes working first. (I've been a bit busy, but it should work by today or tomorrow) and then I'll be willing to merge it. It's better to have most, if not all of the previous functionality working.

**Comment by Sourcastic** [comment] 2024-03-12 06:01
I've just merged #58, if anyone could test out the install script in its entirety, that'd be great. Things to look out for here are the splash screen should work and also not appear in the global theme settings page.

After this, I think all our work is done unless there are any other suggestions.

**Comment by Bartus-OwO** [comment] 2024-03-12 16:05
For me also works perfectly fine on Arch Linux Plasma 6 x11 and also have issue with cursor where cursor reverts to default on some apps and while hovering over the desktop. I fixed cursor with installing cursor from clicking get new in cursor settings.

**Comment by Sourcastic** [comment] 2024-03-12 16:54
> Oh, I... didn't pay attention to that. Sorry, will try again!

No problem, I should've made that clear.



> Alright, works perfectly fine on EndeavourOS Plasma 6 x11, including the splash screen. There's a weird quirk where the cursor reverts to default on KDE applications like Konsole and System Settings, and while hovering over the desktop/panels, but I don't know if that's intended behavior or not.
> 
> Note: I did log out and back in and also created the link that was suggested for inconsistent cursor behavior.

Great!! That means everything is working as intended. The cursor weirdness is a KDE issue. 
As for the splash screen, that should be in ~/.local/share/plasma/look-and-feel and then they should be within one of the theme folders or have their own. Similarly, the aurorae themes should be in ~/.local/share/aurorae if you wanna delete that. No idea how the plasma 6 transition affects that.

**Comment by Sourcastic** [comment] 2024-03-12 16:55
> For me also works perfectly fine on Arch Linux Plasma 6 x11 and also have issue with cursor where cursor reverts to default on some apps and while hovering over the desktop. I fixed cursors with installing cursors from get new in cursor settings.

Hm, the cursor weirdness existed prior too, but it not doing that on the "Get New Stuff" button is interesting. Perhaps it runs the `ln` command or something? Because that and a restart usually fixes it.

**Comment by Sourcastic** [comment] 2024-03-12 16:56
Well, I don't see anything here that isn't intentional. I'll work on trying to make a release for everything in the main branch and then merging the dev branch. Tysm everyone!

**Comment by dinckelman** [comment] 2024-03-12 18:17
> > For me also works perfectly fine on Arch Linux Plasma 6 x11 and also have issue with cursor where cursor reverts to default on some apps and while hovering over the desktop. I fixed cursors with installing cursors from get new in cursor settings.
> 
> Hm, the cursor weirdness existed prior too, but it not doing that on the "Get New Stuff" button is interesting. Perhaps it runs the `ln` command or something? Because that and a restart usually fixes it.

I imagine that's an issue with how the cursor and icon cache works, which would make sense, if a session restart fixes it. I've not experienced this issue on Wayland personally

**Comment by Sourcastic** [comment] 2024-03-13 02:44
Yup, that's likely what it is. Nothing we can do about that, unfortunately.

**Comment by Cequallium** [comment] 2024-03-14 15:42
just installed it on plasma 6, seems to be working perfectly

**Closed** 2024-03-15 14:25 UTC
